name: Jekyll

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/docs/jekyll -v ${{ github.workspace }}/_site:/srv/docs/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod a+w /srv/docs/jekyll/Gemfile.lock && chmod 777 /srv/docs/jekyll && jekyll build --future"
